### ISSUE TITLE
I cannot get pdf_page_size='Unspecified' working in conn.create_subscription()

### ISSUE THREAD

**Issue by iibarant** [divinorum-webb/tableau-api-lib#109]
I really need to set up pdf subscription request with pdf_page_size='Unspecified', but that returns an error:

 _invalid_parameter_exception
    raise InvalidParameterException(class_name=self.__class__.__name__, parameters=vars(self))

InvalidParameterException: 
        "
CreateSubscriptionRequest received an invalid combination of parameters.

...
'_pdf_page_orientation': 'Portrait', '_pdf_page_size': 'Unspecified', '_send_view_if_empty_flag': True}

Is this possible to fix?

**Comment by divinorum-webb** [comment]
The REST API does not support that option. You can look up the available options in Tableau's API reference and you will find this info on the page type/size:

"(Optional) The type of page, which determines the page dimensions of the .pdf file returned. The value can be: A3, A4, A5, B5, Executive, Folio, Ledger, Legal, Letter, Note, Quarto, or Tabloid.

If this parameter is not present the page type will default to Legal."

I typically use A4 with decent results. The exception you see thrown is due to "Unspecified" not being an option provided by Tableau in their API docs.
