### ISSUE TITLE
Filters not passed when querying view data

### ISSUE THREAD

**Issue by azdoherty** [divinorum-webb/tableau-api-lib#13]
No parameters are passed when the request is made, nothing is actually being done with them inside of `ViewEndpoint` so they can either be handled there or added to the request. 

```
self.active_endpoint = ViewEndpoint(ts_connection=self,
                                            view_id=view_id,
                                            query_view_data=True,
                                            parameter_dict=parameter_dict).get_endpoint()
self.active_headers = self.default_headers
response = requests.get(url=self.active_endpoint, headers=self.active_headers, verify=self.ssl_verify)
return response
```

**Comment by divinorum-webb** [comment]
Closing this issue, as discussed in the related pull request thread.

To summarize, we are sticking with `parameter_dict` as-is because:
(a) the existing implementation supports passing filters in the format used within the REST API reference documentation
(b) the view filters are a special case of URL parameters, and the existing implementation supports passing any arbitrary URL parameter (pagination, view filters, sorting, boolean flags, etc)
