### ISSUE TITLE
Create site not working 

### ISSUE THREAD

**Issue by vickyboston20** [divinorum-webb/tableau-api-lib#41]
Hi only create site not working , i dont want to use another TSC library for just create site . So im raising this issue.
Python: 3.6
Tableau api: 3.11
**Steps to reproduce:**
`from tableau_api_lib import TableauServerConnection

tableau_config = {
    'tableau_prod': {
        'server': server,
        'api_version': api,
        'username': username,
        'password': password,
        'site_name': '',
        'site_url': ''
    }
}
conn = TableauServerConnection(tableau_config, env='tableau_prod')
conn.create_site(site_name='estam_temp', content_url='estamTemp')`

**Error:**

`{'error': {'summary': 'Bad Request', 'detail': 'Deserialization problem: Cannot deserialize instance of `java.lang.Boolean` out of START_ARRAY token\n at [Source: (StringReader); line: 1, column: 113] (through reference chain: com.tableausoftware.api.rest.viewmodels.TsRequest["site"]->com.tableausoftware.api.rest.viewmodels.SiteType["dataAlertsEnabled"]); ', 'code': '400000'}}`

**Comment by divinorum-webb** [comment]
Hi @vickyboston20 thanks for calling this out.
I have pushed a temporary fix which simply disables all of the optional parameters that are triggering Java errors on the Tableau Server side. This method should now work for you (`pip install -U tableau-api-lib`).

This isn't the only issue that has entered the picture since the latest version of Tableau Server (and Tableau Online) was released. I'm going to verify whether or not these optional parameters were an issue in the previous versions, and based on those results I'll reach out to the Tableau team accordingly.

Here is a complete list of the temporary optional parameters that have been disabled:
```
[
            "dataAlertsEnabled",
            "commentingMentionsEnabled",
            "catalogObfuscationEnabled",
            "flowAutoSaveEnabled",
            "webExtractionEnabled",
            "metricsContentTypeEnabled",
            "notifySiteAdminsOnThrottle",
            "authoringEnabled",
            "customSubscriptionEmailEnabled",
            "customSubscriptionEmail",
            "customSubscriptionFooterEnabled",
            "customSubscriptionFooter",
            "askDataMode",
            "namedSharingEnabled",
            "mobileBiometricsEnabled",
            "sheetImageEnabled",
            "catalogingEnabled",
            "derivedPermissionsEnabled",
            "userVisibilityMode",
            "useDefaultTimeZone",
            "timeZone",
            "autoSuspendRefreshEnabled",
            "autoSuspendRefreshInactivityWindow"
]
```

**Comment by vickyboston20** [comment]
Hi @divinorum-webb i checked it once then i checked it twice. Now its working fine :> 
Thanks for your quick response much appreciated.
