### ISSUE TITLE
Sign-in: No authentication credentials were provided

### ISSUE THREAD

**Issue by zack-nguyen** [divinorum-webb/tableau-api-lib#50]
Hi @divinorum-webb ,
I tried your sample code below
> creates a Tableau Server connection and prints the response from invoking the REST API's "query_sites" method.
from tableau_api_lib import TableauServerConnection
tableau_config = {
    'tableau_prod': {
        'server': 'https://myserver.com',
        'api_version': '3.11',
        'username': 'myusername',
        'password': 'mypassword',
        'site_name': 'Default',
        'site_url': 'https://myserver.com/#',
        'cache_buster': '',
        'temp_dir': ''
    }
}
connection = TableauServerConnection(config_json=tableau_config, env='tableau_prod', ssl_verify= False)
connection.sign_in()
print(connection.query_sites().json())

 and received this error: 
> {'error': {'summary': 'Unauthorized Access', 'detail': 'No authentication credentials were provided.', 'code': '401000'}}

I was able to use similar format to sign in with tableauserverclient package
Note: my user is server administrator and has all privileges

**Comment by divinorum-webb** [comment]
Hey @zack-nguyen the `site_url` should not be the actual server address, it should be the site name as it appears in your browser. For the default site you can use:
'site_name': 'Default',
'site_url': ''

Or you could also do:
'site_name': '',
'site_url': ''

The site URL / content URL / site ID (it has many names, and site ID is the most confusing because it is NOT the same thing as the site ID in the REST API world) is often the same as the site name. The only time it is different is when the site name has characters that cannot be displayed in a URL. For example, if my site name was "My Cool Site" then the site URL / content URL would likely be "My%20Cool%20Site".

Hope that helps!

**Comment by zack-nguyen** [comment]
Thanks for your quick response. Perfect clarification, that solved my issue
