### ISSUE TITLE
<Response [401]> when using personal access token

### ISSUE THREAD

**Issue by BernardoGui** [divinorum-webb/tableau-api-lib#7]
I am having problems to establish a connection:

```
tableau_server_config = {
        'my_env': {
                'server': '<URL>',
                'site_url': '<URL>/#',
                'site_name': 'Default',
                'api_version': '3.8',
                'personal_access_token_name': '<token_name>', 
                'personal_access_token_secret': '<token_secret>'
        }
}
conn = TableauServerConnection(tableau_server_config, env='my_env')
conn.sign_in()
```
fails with `<Response [401]>`

Login with TSC works:
```
tableau_auth = TSC.PersonalAccessTokenAuth('<token_name>',  '<token_secret>')
server = TSC.Server('<URL>', use_server_version=True)
server.auth.sign_in(tableau_auth)
```

**Comment by divinorum-webb** [comment]
Hi Bernardo, I believe your site_url is being configured incorrectly. This can be confusing because Tableau's site / content url is not in fact the URL, it is the site name as it appears in the URL.

Here is a sample configuration:
{
        'server': 'https://10ax.online.tableau.com',
        'api_version': '3.9',
        'personal_access_token_name': '<name>',
        'personal_access_token_secret': '<secret>',
        'site_name': 'estamdevdev348344',
        'site_url': 'estamdevdev348344'
    }

You can find your site url by looking at the full Tableau Server url when you are logged in. Just think of this as your site name, but as it appears in the url. Often times the site url (or content url) is the same as your site name, but if you had a site name like 'one two three' the site url would be modified to 'onetwothree' to conform to acceptable text existing within a url.

Hope that helps!

**Comment by divinorum-webb** [comment]
And if you are using the default site on Tableau Server, simply leave the entries for 'site_name' and 'site_url' as empty quotations ('').
