### ISSUE TITLE
flatten_dict_list_column is deprecated

### ISSUE THREAD

**Issue by Scatalina1** [divinorum-webb/tableau-api-lib#77]
When applying the flatten_dict_list_column function I receive the following warning:

```
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.   
flattened_col_df = flattened_col_df.append(temp_df)
```

**Comment by divinorum-webb** [comment]
Hi @Scatalina1, thanks for your diligence in calling this out! This warning is issued by Pandas to alert users to a future deprecation of the `append` method on Pandas DataFrames and is not an indication that any feature in the `tableau-api-lib` will be deprecated.

The library will switch to using `concat` instead of `append` before the Pandas library deprecates `append`.
