### ISSUE TITLE
query.Get_Users_DataFrame has two missing columns in new version

### ISSUE THREAD

**Issue by alitwaij** [divinorum-webb/tableau-api-lib#91]
Hi i noticed in the version i downloaded on 28 july 22 that get users method was mssing email and FullName from the columns that existed in version 0.1.37 (downloaded around Aug 2021). Plz can they be added back.

**Comment by divinorum-webb** [comment]
Hi @alitwaij this change was made to avoid errors related to Tableau's REST API failing to support the `_all_` fields parameter for an increasing number of endpoints. It began with the endpoints related to views and has recently impacted the projects endpoints as well.

For now the relevant users endpoint supports the field, so if you run `pip install -U tableau-api-lib` then you will once again be getting the information you expect when running the same code as before. However, if at any point in the future you begin to get errors when using the `get_users_dataframe` function, be aware that you can now pass in a parameter "all_fields". If you begin to get errors in the future then the issue impacting other endpoints may be impacting the "Query Users on Site" endpoint. 

If that scenario above happens then it means that until Tableau fixes the issue impacting these endpoints, you will need to query the `_default_` fields instead of `_all_` fields. You can do this in the following way:
`users_df = querying.get_users_dataframe(conn, all_fields=False)`

Let me know if all is working as expected for you! Sorry for the inconvenience that caused.

**Comment by alitwaij** [comment]
Brilliant many thanks indeed. Very useful info. Your library really helped me in my work. Am really grateful to you.

Thankyou

Ali
________________________________
